Issue #50: HTTP errors are ignored and result in empty responses with…
ipinfo/java pull request #55
Opened 2024-09-11 17:46 UTC by tdltdl

… cache poisoning.

WARNING This change is not a drop in replacement as if we get 403 because the token is incorrect, a checked exception is raised. 

Also note that, if an empty or null token is passed, it is now a fail fast (instead of getting a null pointer exception at the first request)

2025-02-22 00:44 UTC, max-ipinfo requested changes
@tdltdl thanks for sending your PR. I will continue to bring timely feedback from now on so we can create new package versions after each PR.

Please go over the exception restructuring suggested, with all HTTP exceptions inheriting from `HttpErrorException`. That includes simplifying all `throws` clauses to `throws HttpErrorException` where it makes sense.

Could you also update `README.md`' s Error section and document the new errors hierarchically?

I'll help you update the documentation for every exception after your next change.

2025-02-22 00:44 UTC, max-ipinfo commented on src/main/java/io/ipinfo/api/IPinfo.java
>          public IPinfo build() {
Shouldn't this have `throws IllegalArgumentException`?

2025-02-22 00:44 UTC, max-ipinfo commented on src/main/java/io/ipinfo/api/errors/InvalidTokenException.java
> +public class InvalidTokenException extends Exception {
Now that we've introduced a proper `HttpErrorException` class, we should have `InvalidTokenException` and `RateLimitedException` also inherit from it, as they are technically exceptions stemming from an HTTP response.

This helps simplify the design (no need to disambiguate everywhere with `throws RateLimitedException, InvalidTokenException` ) and it also helps clarify (in code) that they stem from the same source.

2025-02-22 00:44 UTC, max-ipinfo commented on src/main/java/io/ipinfo/api/request/BaseRequest.java
> +    public abstract T handle() throws RateLimitedException, InvalidTokenException;
This can be simplified to `throws HttpErrorException`

2025-02-22 00:44 UTC, max-ipinfo commented on src/main/java/io/ipinfo/api/request/BaseRequest.java
> +    public Response handleRequest(Request.Builder request) throws RateLimitedException, InvalidTokenException {
Similarly, this can be simplified `throws HttpErrorException`

2026-02-17 21:18 UTC, closed without merging

2026-02-17 21:50 UTC, tdltdl commented
Why has this PR been closed without merge? This leads to cache poisoning...

2026-02-17 22:15 UTC, max-ipinfo commented
@tdltdl this PR has been stale for a very long time and the comments have not been addressed.

I'll let @silvanocerza decide if he wants to revive this PR.

Thanks for your understanding.

2026-02-17 23:34 UTC, tdltdl commented
In this case the maintainer didn't act on it for a long time. I am a bit surprised you want your Cust to have their cache poisoned with incorrect data. It also appears that strongly type exception to make API explicit and help Cus t know what they need to handle is not a design goal.